default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'user_name' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'user_password' } %>
  host: <%= ENV.fetch('MYSQL_HOST') { '127.0.0.1' } %>

development:
  <<: *default
  database: webapp_development

test:
  <<: *default
  database: webapp_test

production:
  <<: *default
  url: <%= ENV['JAWSDB_URL']&.sub('mysql://', 'mysql2://') %>